version: '3.8'

services:
  face-recognition:
    build:
      context: .
      dockerfile: Dockerfile    # This specifies which Dockerfile to use
    ports:
      - "2000:2000"           # Maps container port to host port
    volumes:
      - ./weights:/app/weights  # Persists model weights
      - ./static:/app/static    # Persists static files
      - ./templates:/app/templates  # Persists templates
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - TF_ENABLE_ONEDNN_OPTS=0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2000/"]
      interval: 30s
      timeout: 10s
      retries: 3 